### ISSUE TITLE
Test failure: Options test fails on en-GB localised machine

### ISSUE THREAD

**Issue by martincostello** [aspnet/Extensions#1203]
### Describe the bug

On a computer where an en-GB locale is used the `Configure_GetsNullableOptionsFromConfiguration(...)` tests fail.

```
Microsoft.Extensions.Options.Tests.OptionsTest.Configure_GetsNullableOptionsFromConfiguration(configValues: [[MyNullableBool, false], [MyNullableInt, -1], [MyNullableDateTime, 31/12/1995]], expectedValues: [[MyNullableBool, False], [MyNullableInt, -1], [MyNullableDateTime, 31/12/1995 00:00:00]])
System.InvalidOperationException : Failed to convert '31/12/1995' to type 'System.DateTime'.\r\n---- System.FormatException : 31/12/1995 is not a valid value for DateTime.\r\n-------- System.FormatException : String '31/12/1995' was not recognized as a valid DateTime.
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options) in C:\Coding\aspnet\Extensions\src\Configuration\Config.Binder\src\ConfigurationBinder.cs:line 303
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options) in C:\Coding\aspnet\Extensions\src\Configuration\Config.Binder\src\ConfigurationBinder.cs:line 209
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options) in C:\Coding\aspnet\Extensions\src\Configuration\Config.Binder\src\ConfigurationBinder.cs:line 184
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options) in C:\Coding\aspnet\Extensions\src\Configuration\Config.Binder\src\ConfigurationBinder.cs:line 342
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions) in C:\Coding\aspnet\Extensions\src\Configuration\Config.Binder\src\ConfigurationBinder.cs:line 119
   at Microsoft.Extensions.Options.NamedConfigureFromConfigurationOptions`1.<>c__DisplayClass1_0.<.ctor>b__0(TOptions options) in C:\Coding\aspnet\Extensions\src\Options\ConfigurationExtensions\src\NamedConfigureFromConfigurationOptions.cs:line 32
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options) in C:\Coding\aspnet\Extensions\src\Options\Options\src\ConfigureNamedOptions.cs:line 50
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name) in C:\Coding\aspnet\Extensions\src\Options\Options\src\OptionsFactory.cs:line 49
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0() in C:\Coding\aspnet\Extensions\src\Options\Options\src\OptionsManager.cs:line 43
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions) in C:\Coding\aspnet\Extensions\src\Options\Options\src\OptionsCache.cs:line 35
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name) in C:\Coding\aspnet\Extensions\src\Options\Options\src\OptionsManager.cs:line 43
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value() in C:\Coding\aspnet\Extensions\src\Options\Options\src\OptionsManager.cs:line 31
   at Microsoft.Extensions.Options.Tests.OptionsTest.Configure_GetsNullableOptionsFromConfiguration(IDictionary`2 configValues, IDictionary`2 expectedValues) in C:\Coding\aspnet\Extensions\src\Options\test\OptionsTest.cs:line 234
----- Inner Stack Trace -----
   at System.ComponentModel.DateTimeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFromInvariantString(String text)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, Object& result, Exception& error) in C:\Coding\aspnet\Extensions\src\Configuration\Config.Binder\src\ConfigurationBinder.cs:line 511
----- Inner Stack Trace -----
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s, IFormatProvider provider)
   at System.ComponentModel.DateTimeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
```

### To Reproduce

Run `build.cmd -test` on a Windows machine using the en-GB locale.

### Expected behavior

The test passes.

**Comment by martincostello** [comment]
See #1204.

**Comment by Tratcher** [comment]
Or should the config binder be culture sensitive? @HaoK?

Having to write all my config dates in InvariantCulture would get annoying. I expect that extends to number formats, etc..

**Comment by martincostello** [comment]
I did consider that, but then that was a turn into an app compatibility thing that I didn't want to get into straight away.

**Comment by Eilon** [comment]
InvariantCulture is usually the right thing for config data. You don't want that varying "randomly" based on whatever culture is set on some random machine.
