### ISSUE TITLE
EF fromSQL throws ArgumentNullException

### ISSUE THREAD

**Issue by YehonatanB** [aspnet/Extensions#1236]
I'm using C# (.net core v2.2) and EF core. I have pretty old code that is retrieving a row from the database:
``` c#
string id = "123";
using (var context = new UsersDb())
{
    var req = context.ScanRequests.FromSql($"EXEC GetById {id}").FirstOrDefault();
    // ...
}
```
GetById is a stored procedure, written in Azure SQL (basically - SQL Server).

This code started to throw an exception recently:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.FromSql[TEntity](IQueryable`1 source, FormattableString sql)
   at ***.***Factory.<>c__DisplayClass0_0.<GetById>b__0() in /tmp/sources/SystemLayer/***/***.cs:line 29
```
This issue doesn't happen to me when I run the same code with the same parameters in a local environment. Also, in most cases it's also working on production servers. I guess it's at least 99.9% success rate.

The problematic line (line 29 from stacktrace) is this line: 
```c#
var req = context.ScanRequests.FromSql($"EXEC GetById {id}").FirstOrDefault();
```

**UPDATE 1**
I thought maybe the problem is because of my mapping to the database - maybe the database schema has been changed without changing the EF accordingly. So I run the mapping command again:

    Scaffold-DbContext "cs" ...

After re-generating the classes again, I found that no file has been changed since my last GIT commit. Therefor, my EF code is already aligned with the database schema.

**UPDATE 2**
I was running my code with EF Nuget package version 2.2.1. I saw that I can update the EF package to 2.2.2. I did it but it isn't solved the issue. Same behavior.

What to do? What else should I check?

### Further technical details
EF Core version: netcoreapp2.2
Database Provider: Azure Sql
Operating system: Linux debian
IDE: Visual Studio 2017 15.9.4

**Comment by anurse** [comment]
This call stack looks a little strange, since we generally have `ConcurrentDictionary`s on this code path. @YehonatanB can you share your startup/configuration logic? Are you using a different DI container from the built-in one?
