### ISSUE TITLE
UseWindowsService should enable EventLog logger by default

### ISSUE THREAD

**Issue by anurse** [aspnet/Extensions#1286]
When you are building a generic host app using Windows Service lifetime, console logging isn't really useful. The EventLog is a good place to log this stuff. We should enable the EventLog logger, or some other relevant logger, by default. We should probably only forward Warnings/Errors to the EventLog to avoid spamming it.

Things to consider:
* EventLog logger isn't a scenario we've really used heavily, it might be ugly
* We log to the "Application" log, which is a pain, but doing anything else requires Admin :(.

**Comment by Tratcher** [comment]
Note I didn't have any permission issues setting the event viewer Source when running as Local System. When I make a base user then this is the error I get:
```
Exception Info: System.AggregateException: An error occurred while writing to logger(s). (The source was not found, but some or all event logs could not be searched.  To create the source, you need permission to read all event logs to make sure that the new source name is unique.  Inaccessible logs: Security, State.) ---> System.Security.SecurityException: The source was not found, but some or all event logs could not be searched.  To create the source, you need permission to read all event logs to make sure that the new source name is unique.  Inaccessible logs: Security, State.
   at System.Diagnostics.EventLog.FindSourceRegistration(String source, String machineName, Boolean readOnly, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source, String machineName, Boolean wantToCreate)
   at System.Diagnostics.EventLogInternal.VerifyAndCreateSource(String sourceName, String currentMachineName)
   at System.Diagnostics.EventLogInternal.WriteEvent(EventInstance instance, Byte[] data, Object[] values)
   at System.Diagnostics.EventLog.WriteEvent(EventInstance instance, Byte[] data, Object[] values)
   at System.Diagnostics.EventLog.WriteEvent(EventInstance instance, Object[] values)
   at Microsoft.Extensions.Logging.EventLog.WindowsEventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category) in D:\github\Extensions\src\Logging\Logging.EventLog\src\WindowsEventLog.cs:line 24
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.WriteMessage(String message, EventLogEntryType eventLogEntryType, Int32 eventId) in D:\github\Extensions\src\Logging\Logging.EventLog\src\EventLogLogger.cs:line 122
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in D:\github\Extensions\src\Logging\Logging.EventLog\src\EventLogLogger.cs:line 114
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in d:\github\Extensions\src\Logging\Logging\src\Logger.cs:line 33
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in d:\github\Extensions\src\Logging\Logging\src\Logger.cs:line 51
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in d:\github\Extensions\src\Logging\Logging.Abstractions\src\LoggerT.cs:line 44
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args) in d:\github\Extensions\src\Logging\Logging.Abstractions\src\LoggerExtensions.cs:line 393
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, String message, Object[] args) in d:\github\Extensions\src\Logging\Logging.Abstractions\src\LoggerExtensions.cs:line 348
   at Microsoft.Extensions.Logging.LoggerExtensions.LogInformation(ILogger logger, String message, Object[] args) in d:\github\Extensions\src\Logging\Logging.Abstractions\src\LoggerExtensions.cs:line 174
   at GenericHostSample.MyServiceB.Dispose() in D:\github\Extensions\src\Hosting\samples\GenericHostSample\MyServiceB.cs:line 52
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync() in D:\github\Extensions\src\DependencyInjection\DI\src\ServiceLookup\ServiceProviderEngineScope.cs:line 109
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync() in D:\github\Extensions\src\Hosting\Hosting\src\Internal\Host.cs:line 115
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token) in D:\github\Extensions\src\Hosting\Abstractions\src\HostingAbstractionsHostExtensions.cs:line 70
   at GenericHostSample.WindowsServiceControlled.Main(String[] args) in D:\github\Extensions\src\Hosting\samples\GenericHostSample\WindowsServiceControlled.cs:line 20
   at GenericHostSample.WindowsServiceControlled.<Main>(String[] args)
```
