### ISSUE TITLE
EventLogLogger doesn't handle null values in logging scopes

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Extensions#1847]
Found when implementing https://github.com/aspnet/AspNetCore/pull/11211. Simple repro:

```C#
var loggerFactory = LoggerFactory.Create(builder =>
{
    builder.AddEventLog();
});
var logger = loggerFactory.CreateLogger("Test");

using (logger.BeginScope(new Dictionary<string, object> { { "Key", null } }))
{
    logger.LogInformation("Hello World");
}
```

```
System.AggregateException: An error occurred while writing to logger(s). (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.<>c__12`1.<Log>b__12_0(Object scope, StringBuilder sb)
   at Microsoft.Extensions.Logging.LoggerExternalScopeProvider.<ForEachScope>g__Report|1_0[TState](Scope current, <>c__DisplayClass1_0`1& )
   at Microsoft.Extensions.Logging.LoggerExternalScopeProvider.ForEachScope[TState](Action`2 callback, TState state)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogInformation(ILogger logger, String message, Object[] args)
   at FrontEnd.Program.Main(String[] args) in C:\Users\david\source\repos\ConferencePlannerv3\FrontEnd\Program.cs:line 24
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.<>c__12`1.<Log>b__12_0(Object scope, StringBuilder sb)
   at Microsoft.Extensions.Logging.LoggerExternalScopeProvider.<ForEachScope>g__Report|1_0[TState](Scope current, <>c__DisplayClass1_0`1& )
   at Microsoft.Extensions.Logging.LoggerExternalScopeProvider.ForEachScope[TState](Action`2 callback, TState state)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)<---
```

**Comment by gfoidl** [comment]
@davidfowl you are already working on the fix? (I saw a branch for that.)
If not, I can take a look.

**Comment by davidfowl** [comment]
Too late 😉
