### ISSUE TITLE
Exceptions in BackgroundService ExecuteAsync are (sometimes) hidden

### ISSUE THREAD

**Issue by drmcclelland** [aspnet/Extensions#2363]
### Describe the bug
Using the dotnet new worker template, I have reproduced a problem that's been causing us problems in our testing.  If an exception occurs inside the overriden `ExecuteAsync()` method of our service that inherits from BackgroundService, **sometimes** it is hidden/lost and the program hangs very ungracefully...

But it's only **sometimes** hidden/lost...   and here's my best triage:  if the exception occurs anywhere before the first "await", then it's NOT hidden/lost.  

### To Reproduce
1. Using version 3.0 preview 9 of the .NET Core SDK
2. Use the dotnet new worker command to generate a new project based on the Worker template
3. Modify the Main() method in Program.cs as follows:
```
        public static void Main(string[] args)
        {
            try
            {
                CreateHostBuilder(args).Build().Run();

                Console.WriteLine("No exception!");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Main method caught exception:  " + ex);
                Environment.Exit(-1);
            }
        }
```

4. Modify Worker.cs as follows (an exception is thrown AFTER the await):
```
    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;

        public Worker(ILogger<Worker> logger)
        {
            _logger = logger;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);

                await Task.Delay(1000, stoppingToken);

                throw new ApplicationException("If an application occurs here, it will NOT bubble up to Main()");
            }
        }
    }

```

5. Run the program, and when the exception occurs it never bubbles up to Main().  The program hangs, and you have to press Ctrl+C to end the application - but you have no indication an exception has occurred:
```
info: WorkerExceptionTest.Worker[0]
      Worker running at: 09/17/2019 16:24:01 -05:00
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\spikes\WorkerExceptionTest
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
No exception!

C:\spikes\WorkerExceptionTest\bin\Debug\netcoreapp3.0\WorkerExceptionTest.exe (process 30284) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

6. Modify Worker.cs as follows (an exception is thrown BEFORE the await):
```
    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;

        public Worker(ILogger<Worker> logger)
        {
            _logger = logger;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);

                throw new ApplicationException("If an application occurs here, it will bubble up to Main()");

                await Task.Delay(1000, stoppingToken);
            }
        }
    }

```

7. Run the program, and when the exception occurs it does bubble up to Main():
```
info: WorkerExceptionTest.Worker[0]
      Worker running at: 09/17/2019 16:28:13 -05:00
Main method caught exception:  System.ApplicationException: If an application occurs here, it will bubble up to Main()
   at WorkerExceptionTest.Worker.ExecuteAsync(CancellationToken stoppingToken) in C:\spikes\WorkerExceptionTest\Worker.cs:line 26
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at WorkerExceptionTest.Program.Main(String[] args) in C:\spikes\WorkerExceptionTest\Program.cs:line 16

C:\spikes\WorkerExceptionTest\bin\Debug\netcoreapp3.0\WorkerExceptionTest.exe (process 20380) exited with code -1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

### Expected behavior
I would expect that no matter WHEN the exception occurs (before or after await) it **would** bubble up to Main().

### Additional context
This may (or may not) be related to #1836 ?

**Comment by drmcclelland** [comment]
Hmmm...   looks like I'm not the only one running into this, here are some StackOverflow questions:

[Exception thrown from task is swallowed if thrown after 'await'](https://stackoverflow.com/questions/56871146)

[.Net core IHostedService Background task exception will not terminate application](https://stackoverflow.com/questions/55483080)

So...    if I log and/or handle the exception inside my BackgroundService / IHostedService, then use an injected IApplicationLifetime to call StopApplication(), maybe my question is a little different:

How can I communicate back to the Main() method that an IHostedService/BackgroundService did not finish successfully?  I would still like to provide an exit code to indicate my process encountered an error (this is an EXE run by a job scheduler).

**Comment by gfoidl** [comment]
You can set the exit-code explicitely, like so
```c#
catch (Exception ex)
{
    _logger.LogError(ex, "Unexpected failure while exuting worker {Name}", this.GetType().Name);
    Environment.ExitCode = 1;
    throw;
}
```

**Comment by drmcclelland** [comment]
Thanks @gfoidl - based on your suggestion, here's the code I've tried that seems to work well, any suggestions / cautions about this approach?

Program.cs:
```
    public class Program
    {
        public static async Task Main(string[] args)
        {
            try
            {
                await CreateHostBuilder(args).RunConsoleAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Main method caught exception:  " + ex);
                Environment.ExitCode = -3;
            }
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();

                    // Uncomment to simulate an exception
                    //throw new ApplicationException("An application startup error occurred, it will be caught by the Main() method");
                });
    }

```

Worker.cs:
```
    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;
        private readonly IHostApplicationLifetime applicationLifetime;

        public Worker(ILogger<Worker> logger, IHostApplicationLifetime applicationLifetime)
        {
            _logger = logger;
            this.applicationLifetime = applicationLifetime;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            try
            {
                // for loop to simulate a long-running process (data import, etc)
                for (int i=0; i <= 10; i++)
                {
                    _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);

                    // Simulate processing time.
                    await Task.Delay(1000);

                    // see if the user pressed Ctrl+C
                    stoppingToken.ThrowIfCancellationRequested();

                    // NOTE:  since Task.Delay() is has an overload that accepts a CancellationToken, the above 2 lines
                    // could be combined as follows:
                    //await Task.Delay(1000, stoppingToken);

                    // Uncomment to simulate an exception.
                    //throw new ApplicationException("An error occurred inside the worker process");
                }

                _logger.LogInformation("Worker process completed successfully");
            }
            catch (OperationCanceledException)
            {
                _logger.LogWarning("Worker process was cancelled");

                Environment.ExitCode = -1;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Worker process caught exception");

                Environment.ExitCode = -2;
            }
            finally
            {
                // No matter what happens (success or exception), we need to indicate that it's time to stop the application.
                applicationLifetime.StopApplication();
            }
        }
    }
```

**Comment by gfoidl** [comment]
Don't use negative `ExitCode`s, just use values in the range `[0, 255]`.
So you're code can run anywhere :wink:

BTW: for logging use scopes, so you don't have to repeat in the message where you are.

**Comment by drmcclelland** [comment]
Thanks @gfoidl!  

Closing issue since I have a better understanding of how exception handling needs to work in ExecuteAsync() - I hope this helps others in the future.
