### ISSUE TITLE
AddAzureWebAppDiagnostics throws an exception if used in combination with azure webapp zip deploy

### ISSUE THREAD

**Issue by saithis** [aspnet/Extensions#2656]
# Describe the bug
AddAzureWebAppDiagnostics throws an exception if used in combination with azure webapp zip deploy.
There is no exception if we deploy the code with Visual Studio (no zip deploy).

### To Reproduce
1. Using version '3.0.0' of package 'Microsoft.Extensions.Logging.AzureAppServices'
2. Run this code:
```
        private static readonly LoggerProviderCollection LoggerProvider = new LoggerProviderCollection();

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    .UseSerilog(providers: LoggerProvider)
                    .ConfigureLogging(config =>
                    {
                        config.ClearProviders();
                        config.SetMinimumLevel(LogLevel.Trace);
                        config.AddAzureWebAppDiagnostics();
                    })
                    .UseStartup<Startup>();
                });
```
3. Deploy to Azure with Zip Deployment/WEBSITE_RUN_FROM_PACKAGE: 1
4. See error:

> System.IO.FileNotFoundException: Error reading the D:\home\site\diagnostics\ directory.
>    at System.IO.FileSystemWatcher.StartRaisingEvents()
>    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
>    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
>    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
>    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
>    at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
>    at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
>    at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
>    at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
>    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>    at Microsoft.Extensions.Logging.AzureAppServices.SiteConfigurationProvider.GetAzureLoggingConfiguration(IWebAppContext context)
>    at Microsoft.Extensions.Logging.AzureAppServicesLoggerFactoryExtensions.AddAzureWebAppDiagnostics(ILoggingBuilder builder, IWebAppContext context)
>    at Microsoft.Extensions.Logging.AzureAppServicesLoggerFactoryExtensions.AddAzureWebAppDiagnostics(ILoggingBuilder builder)
>    at Prosoft.Tenant.Api.Program.<>c.<CreateHostBuilder>b__1_2(ILoggingBuilder config) in C:\j\ws\Recruiting\prosoft-recruiting-qa\Prosoft.Tenant.Api\Program.cs:line 66
>    at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass8_0.<ConfigureLogging>b__0(IServiceCollection collection)
>    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureServices>b__0(WebHostBuilderContext context, IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(HostBuilderContext context, IServiceCollection builder)
>    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
>    at Microsoft.Extensions.Hosting.HostBuilder.Build()

### Expected behavior
It should find and be able to read the D:\home\site\diagnostics\settings.json, as it is definitelly there.

### Additional context
We use AspNetCoreModuleV2 with InProcess hosting and .NET Core 3.0

**Comment by saithis** [comment]
Some additional notes: 
With .NET Core 2.2 we used Serilog.Sinks.AzureApp (https://github.com/cnelsonakgov/serilog-sinks-azureapp) and the logging to Azure WebApp Diagnostics worked. 
After upgrading to .NET Core 3.0 the logging failed silently, so we removed Serilog.Sinks.AzureApp and rewrote the logging to the code shown above, which resulted in the exception. So I suspect that Serilog.Sinks.AzureApp got the same exception and just swallowed it.

**Comment by M-Wildgruber** [comment]
We encounter the exact same error for one of our solutions. When deploying from VS2019, the application starts without a problem, but when deployed through an Azure Pipelines Release pipeline, the application fails to start with the error message shown above. The release task defaults to "run from package". 
The Azure Web App uses a windows host. We also used Kudu and even accessed D:\home\site\diagnostics from our code successfully (as long as we did not include the code to configure logging with AddAzureWebAppDiagnostics.
Unfortunately, we were unable to reproduce the behavior for a smaller solution.

**Comment by saithis** [comment]
I did some further testing and it seems like the diagnostics folder is the problem.

I used this code:

```
var dirPath = "D:\\home\\site\\diagnostics";
var filePath = $"{dirPath}\\settings.json";
Log.Error($"Directory.Exists: {Directory.Exists(dirPath)}");
Log.Error($"File.Exists: {File.Exists(filePath)}");
logpathfiles("D:\\home\\site");
logpathfiles("D:\\home\\site\\diagnostics");
void logpathfiles(string path)
{
    try
    {
        Log.Error($"Path: {path}");
        Log.Error($"Directory.GetDirectories: {string.Join(",", Directory.GetDirectories(path))}");
        Log.Error($"Directory.GetFiles: {string.Join(",", Directory.GetFiles(path))}");
    }
    catch (Exception e)
    {
        Log.Error(e, "logpathfiles failed");
    }
}
```

and got this result:

```
[ERR] Directory.Exists: True
[ERR] File.Exists: False
[ERR] Path: D:\home\site
[ERR] Directory.GetDirectories: D:\home\site\deployments,D:\home\site\diagnostics,D:\home\site\locks,D:\home\site\logs,D:\home\site\wwwroot
[ERR] Directory.GetFiles: 
[ERR] Path: D:\home\site\diagnostics
[ERR] logpathfiles failed 
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\home\site\diagnostics'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path)
   at (omitted).Program.<Main>g__logpathfiles|2_0(String path) in C:\(omitted)\Program.cs:line 98
```

Somehow the diagnostics folder is there, but not accessible from code. If I try to open the folder and settings.json from kudu, it works.

**Comment by BrennanConroy** [comment]
@suwatch Is there anything odd about the `D:\home\site\diagnostics` directory that would cause failures when trying to path traverse it in .NET?
