### ISSUE TITLE
[Helix] Logging analyzer test fails on all platforms/frameworks

### ISSUE THREAD

**Issue by HaoK** [aspnet/Extensions#625]
Tons of failures that look like this, @pakrym do you own these tests?  Do you have any ideas why these would all fail like these?  We are copying the publish directory for these tests and running them on the 2.1 sdk + 2.1.6 runtime, do these tests depend on something different to pass?

https://mc.dot.net/#/user/dotnet-github-anon-kaonashi-bot/pr~2Faspnet~2Fextensions/ci/20181210.14/workItem/Microsoft.Extensions.Logging.Analyzer.Tests~2Fnetcoreapp2.0/wilogs

```
Starting test execution, please wait...
[xUnit.net 00:00:03.32]     TemplateDiagnosticsAreNotProduced(format: "logger.LogDebug(\"{camelCase}\", 1);") [FAIL]
[xUnit.net 00:00:03.41]     TemplateDiagnosticsAreNotProduced(format: "logger.LogCritical(1, new System.Exception(), \" s"...) [FAIL]
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogDebug(\"{camelCase}\", 1);")
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogCritical(1, new System.Exception(), \" s"...)
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
[xUnit.net 00:00:03.55]     TemplateDiagnosticsAreNotProduced(format: "LoggerMessage.DefineScope<int>(\"{camelCase}\");") [FAIL]
[xUnit.net 00:00:03.59]     TemplateDiagnosticsAreNotProduced(format: "logger.LogDebug(\"{st\" + \"ring}\", 1);") [FAIL]
[xUnit.net 00:00:03.64]     TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace($\" string\" + $\" string\");") [FAIL]
[xUnit.net 00:00:03.67]     TemplateDiagnosticsAreNotProduced(format: "logger.LogWarning(1, new System.Exception(), nameo"...) [FAIL]
[xUnit.net 00:00:03.72]     TemplateDiagnosticsAreNotProduced(format: "logger.LogWarning(0, \"{st\" + \"ring}\", 1);") [FAIL]
[xUnit.net 00:00:03.75]     TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace(0, \"{st\" + \"ring}\", 1);") [FAIL]
[xUnit.net 00:00:03.78]     TemplateDiagnosticsAreNotProduced(format: "logger.LogDebug(2, null, nameof(ILogger) + \" stri"...) [FAIL]
[xUnit.net 00:00:03.81]     TemplateDiagnosticsAreNotProduced(format: "logger.LogError(\"{camelCase}\", 1);") [FAIL]
[xUnit.net 00:00:03.85]     TemplateDiagnosticsAreNotProduced(format: "logger.LogInformation(\"{st\" + \"ring}\", 1);") [FAIL]
Failed   TemplateDiagnosticsAreNotProduced(format: "LoggerMessage.DefineScope<int>(\"{camelCase}\");")
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogDebug(\"{st\" + \"ring}\", 1);")
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace($\" string\" + $\" string\");")
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogWarning(1, new System.Exception(), nameo"...)
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogWarning(0, \"{st\" + \"ring}\", 1);")
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace(0, \"{st\" + \"ring}\", 1);")
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogDebug(2, null, nameof(ILogger) + \" stri"...)
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogError(\"{camelCase}\", 1);")
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogInformation(\"{st\" + \"ring}\", 1);")
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
[xUnit.net 00:00:03.89]     TemplateDiagnosticsAreNotProduced(format: "logger.LogDebug(2, null, \" string\" + \" string\""...) [FAIL]
[xUnit.net 00:00:03.93]     TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace(1, new System.Exception(), \"{came"...) [FAIL]
[xUnit.net 00:00:03.96]     TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace(0, $\" string\" + $\" string\");") [FAIL]
[xUnit.net 00:00:04.00]     TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace(\"{camelCase}\", 1);") [FAIL]
[xUnit.net 00:00:04.04]     TemplateDiagnosticsAreNotProduced(format: "LoggerMessage.Define<int>(LogLevel.Information, 42"...) [FAIL]
[xUnit.net 00:00:04.10]     TemplateDiagnosticsAreNotProduced(format: "logger.LogInformation(2, null, \"{string} {string}"...) [FAIL]
[xUnit.net 00:00:04.13]     TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace(1, new System.Exception(), \" stri"...) [FAIL]
[xUnit.net 00:00:04.17]     TemplateDiagnosticsAreNotProduced(format: "logger.LogError(2, null, $\" string\" + $\" string"...) [FAIL]
[xUnit.net 00:00:04.20]     TemplateDiagnosticsAreNotProduced(format: "logger.LogDebug(0, $\" string\" + $\" string\");") [FAIL]
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogDebug(2, null, \" string\" + \" string\""...)
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace(1, new System.Exception(), \"{came"...)
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace(0, $\" string\" + $\" string\");")
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace(\"{camelCase}\", 1);")
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "LoggerMessage.Define<int>(LogLevel.Information, 42"...)
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogInformation(2, null, \"{string} {string}"...)
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogTrace(1, new System.Exception(), \" stri"...)
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error CS0518: Predefined type 'System.Object' is not defined or imported, Test0(3,14): error CS1729: 'object' does not contain a constructor that takes 0 arguments, Test0(5,18): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(5,33): error CS0518: Predefined type 'System.String' is not defined or imported, Test0(6,19): error CS0518: Predefined type 'System.Void' is not defined or imported, ...]
Stack Trace:
   at Microsoft.Extensions.Logging.Analyzer.Test.FormatStringAnalyzerTests.TemplateDiagnosticsAreNotProduced(String format) in /_/src/Logging/Logging.Analyzers/test/FormatStringAnalyzerTests.cs:line 96
Failed   TemplateDiagnosticsAreNotProduced(format: "logger.LogError(2, null, $\" string\" + $\" string"...)
Error Message:
 Assert.Empty() Failure
Collection: [Test0(3,14): error
```

**Comment by pakrym** [comment]
They use dependency model (and PreserveCompilationOptions) to create an in-memory Roslyn solution to run tests against. This might happen if compilation assemblies were not resolved correctly. Do MVC Analyzers work?

**Comment by HaoK** [comment]
We are starting with only extensions to run helix tests, so we aren't trying MVC yet, I would guess they would suffer from similar issues.  I don't see these failures locally so there must be something different about our dev machines after a build/run that these tests depend on.  Is there a sideeffect that these tests rely on?

**Comment by pakrym** [comment]
It relies on package cache when you run using `dotnet test` but if you publish test projects everything required should be in-place. Did you try running published tests on a clean machine manually?

**Comment by HaoK** [comment]
Yes so this is broken locally as well to repro:

In src\Logging\Logging.Analyzers
```
dotnet publish
cd src\Logging\Logging.Analyzers\test\bin\Debug\netcoreapp2.1\publish
dotnet vstest .\Microsoft.Extensions.Logging.Analyzer.Tests.dll
```

**Comment by pakrym** [comment]
I'll take a look.

**Comment by HaoK** [comment]
Awesome thanks
