### ISSUE TITLE
Often a timeout

### ISSUE THREAD

**Issue by wanghaoxing** [aspnet/Extensions#701]
``` json
Timeout performing EVAL, inst: 5, queue: 1, qu: 0, qs: 1, qc: 0, wr: 0, wq: 0, in: 19, ar: 0, clientName: , serverEndpoint: 172.16.0.146:6379, keyHashSlot: 12452 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)- at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1052
at Microsoft.Extensions.Caching.Redis.RedisExtensions.HashMemberGet(IDatabase cache, String key, String[] members)
at Microsoft.Extensions.Caching.Redis.RedisCache.GetAndRefresh(String key, Boolean getData)
at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetString(IDistributedCache cache, String key)
```

**Comment by 3rzx** [comment]
Hi @bragma I deal with the same problem, too. Thanks for your answer. But I also use ThreadPool.SetMaxThreads(...) to limit the number of threads. I wonder is there any principle about setting number of MaxThreads and MinThreads ?

**Comment by anurse** [comment]
Thread pool starvation issues like this are a frequent problem when you use synchronous *blocking* APIs like `GetString`. You should use something like `GetStringAsync` instead to avoid locking up thread-pool threads. .NET has a limited number of thread-pool threads and any time you call one of these synchronous APIs (or call `.Wait` or `.Result` on a `Task`) you are locking-up one of these threads.

You already appear to be in an `async` method, so you should use the `GetStringAsync` method instead.

We should provide better documentation or guidance here (via deprecating functions), so I filed https://github.com/aspnet/Extensions/issues/1893 to do that.

**Comment by bragma** [comment]
@anurse my code is entirely async, I never use blocking version of a method if there is an equivalent async. Still, I have the problem when my azure web app restarts after  a deploy/slot swap. Increasing the thread pool mitigates it.

**Comment by anurse** [comment]
Sounds like that's likely a different issue then. The original code sample provided **did** use blocking methods.
