### ISSUE TITLE
Minimal .NET Frameworks supported version 

### ISSUE THREAD

**Issue by hellboy81** [aspnet/Extensions#784]
Trying to install into .NET 4.6.1 /C' 5.0 project, got:

```
------- Installing...Microsoft.Extensions.Configuration.Json 2.1.1 -------
Adding 'Microsoft.Extensions.Configuration.Json 2.1.1' to ....
System.InvalidOperationException: Could not install package 'Microsoft.Extensions.Configuration.Json 2.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
   at NuGet.ProjectManager.ExtractPackageFilesToProject(IPackage package)
   at NuGet.ProjectManager.AddPackageReferenceToProject(IPackage package)
   at NuGet.ProjectManager.Execute(PackageOperation operation)
   at NuGet.ProjectManager.Execute(IPackage package, IPackageOperationResolver resolver)
   at NuGet.ProjectManager.AddPackageReference(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at NuGet.ProjectManager.AddPackageReference(String packageId, SemanticVersion version, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at ICSharpCode.PackageManagement.SharpDevelopPackageManager.AddPackageReference(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at ICSharpCode.PackageManagement.SharpDevelopPackageManager.InstallPackage(IPackage package, InstallPackageAction installAction)
   at ICSharpCode.PackageManagement.PackageManagementProject.InstallPackage(IPackage package, InstallPackageAction installAction)
   at ICSharpCode.PackageManagement.InstallPackageAction.ExecuteCore()
   at ICSharpCode.PackageManagement.ProcessPackageAction.<Execute>b__35_0()
   at ICSharpCode.PackageManagement.ProcessPackageAction.RunWithExceptionReporting(Action action)
   at ICSharpCode.PackageManagement.ProcessPackageAction.Execute()
   at ICSharpCode.PackageManagement.PackageActionRunner.Run(IPackageAction action)
   at ICSharpCode.PackageManagement.PackageViewModel.InstallPackageIntoProject(IEnumerable`1 installOperations)
   at ICSharpCode.PackageManagement.PackageViewModel.TryAddingPackage()
==============================

------- Installing...Microsoft.Extensions.Configuration 2.1.1 -------
Installing 'Microsoft.Extensions.Configuration 2.1.1'.
Added file 'Microsoft.Extensions.Configuration.dll' to folder 'Microsoft.Extensions.Configuration.2.1.1\lib\netstandard2.0'.
Added file 'Microsoft.Extensions.Configuration.xml' to folder 'Microsoft.Extensions.Configuration.2.1.1\lib\netstandard2.0'.
Added file 'Microsoft.Extensions.Configuration.2.1.1.nupkg' to folder 'Microsoft.Extensions.Configuration.2.1.1'.
Successfully installed 'Microsoft.Extensions.Configuration 2.1.1'.
Adding 'Microsoft.Extensions.Configuration 2.1.1' to Testauto.
System.InvalidOperationException: Could not install package 'Microsoft.Extensions.Configuration 2.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
   at NuGet.ProjectManager.ExtractPackageFilesToProject(IPackage package)
   at NuGet.ProjectManager.AddPackageReferenceToProject(IPackage package)
   at NuGet.ProjectManager.Execute(PackageOperation operation)
   at NuGet.ProjectManager.Execute(IPackage package, IPackageOperationResolver resolver)
   at NuGet.ProjectManager.AddPackageReference(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at NuGet.ProjectManager.AddPackageReference(String packageId, SemanticVersion version, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at ICSharpCode.PackageManagement.SharpDevelopPackageManager.AddPackageReference(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at ICSharpCode.PackageManagement.SharpDevelopPackageManager.InstallPackage(IPackage package, InstallPackageAction installAction)
   at ICSharpCode.PackageManagement.PackageManagementProject.InstallPackage(IPackage package, InstallPackageAction installAction)
   at ICSharpCode.PackageManagement.InstallPackageAction.ExecuteCore()
   at ICSharpCode.PackageManagement.ProcessPackageAction.<Execute>b__35_0()
   at ICSharpCode.PackageManagement.ProcessPackageAction.RunWithExceptionReporting(Action action)
   at ICSharpCode.PackageManagement.ProcessPackageAction.Execute()
   at ICSharpCode.PackageManagement.PackageActionRunner.Run(IPackageAction action)
   at ICSharpCode.PackageManagement.PackageViewModel.InstallPackageIntoProject(IEnumerable`1 installOperations)
   at ICSharpCode.PackageManagement.PackageViewModel.TryAddingPackage()
==============================
```

**Comment by pranavkm** [comment]
> Trying to install into .NET 4.6.1 

The error message suggests that you're attempting to install this in a .NET 4.6 targeting project. 

> You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework

The 2.1 version of Extensions package support .NET 4.6.1 at minimum.
