### ISSUE TITLE
HostBuilder: IConfiguration setter

### ISSUE THREAD

**Issue by cheng93** [aspnet/Extensions#811]
When using `HostBuilder` without `ConfigureHostConfiguration` and using a setter on `IConfiguration` this throws an exception.

Is this intended?

Exception details

```
System.InvalidOperationException
  HResult=0x80131509
  Message=A configuration source is not registered. Please register one before setting a value.
  Source=Microsoft.Extensions.Configuration
  StackTrace:
   at Microsoft.Extensions.Configuration.ConfigurationRoot.set_Item(String key, String value)
   at Microsoft.Extensions.Configuration.ConfigurationRoot.set_Item(String key, String value)
   at ConsoleApp1.Program.Main(String[] args)
```

Source

```
namespace ConsoleApp1
{
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;

    class Program
    {
        static void Main(string[] args)
        {
            var host = CreateHostBuilder(args).Build();
            var config = host.Services.GetService<IConfiguration>();

            config["Foo"] = "Bar";

            host.Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            new HostBuilder()
                .ConfigureAppConfiguration((context, configuration) => { configuration.AddEnvironmentVariables(); });
    }
}
```

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.2.0-preview2-35157" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="2.2.0-preview2-35157" />
  </ItemGroup>

</Project>
```

**Comment by muratg** [comment]
@Tratcher Do you propose any changes in 3.0?
